spring.application.name=teletrabajo
spring.jackson.time-zone=America/Santiago
spring.jpa.properties.hibernate.jdbc.time_zone=America/Santiago

spring.datasource.url=jdbc:h2:mem:teletraajo
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# application.properties
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

server.error.include-message=always
server.error.include-stacktrace=always

# JWT
app.jwt.secret=change_me_with_a_very_long_random_256bit_secret___________________________

# Access token (1 hora)
app.jwt.expiration-ms=3600000

# Refresh token (7 das)
app.jwt.refresh-expiration-ms=604800000


logging.level.org.springframework.security=DEBUG
